// AUTO-GENERATED by scripts/gen-hero-manifest.mjs — 직접 수정하지 말 것.
// public/images/hero 스캔 결과: "{시간}_{날씨}" → { breed, pc, m }.
// 영상 추가/교체 후 `node scripts/gen-hero-manifest.mjs`(또는 npm run dev/build)로 갱신됨.
export const HERO_VIDEO_MANIFEST = {
    "afternoon_cloudy": {
        "breed": "welshcorgi",
        "pc": "/images/hero/summer_afternoon_cloudy_welshcorgi_pc.mp4",
        "m": "/images/hero/summer_afternoon_cloudy_welshcorgi_m.mp4"
    },
    "afternoon_rain": {
        "breed": "englishbulldog",
        "pc": "/images/hero/summer_afternoon_rain_englishbulldog_pc.mp4",
        "m": "/images/hero/summer_afternoon_rain_englishbulldog_m.mp4"
    },
    "afternoon_sunny": {
        "breed": "poodle",
        "pc": "/images/hero/summer_afternoon_sunny_poodle_pc.mp4",
        "m": "/images/hero/summer_afternoon_sunny_poodle_m.mp4"
    },
    "evening_cloudy": {
        "breed": "welshcorgi",
        "pc": "/images/hero/summer_evening_cloudy_welshcorgi_pc.mp4",
        "m": "/images/hero/summer_evening_cloudy_welshcorgi_m.mp4"
    },
    "evening_rain": {
        "breed": "englishbulldog",
        "pc": "/images/hero/summer_evening_rain_englishbulldog_pc.mp4",
        "m": "/images/hero/summer_evening_rain_englishbulldog_m.mp4"
    },
    "evening_sunny": {
        "breed": "poodle",
        "pc": "/images/hero/summer_evening_sunny_poodle_pc.mp4",
        "m": "/images/hero/summer_evening_sunny_poodle_m.mp4"
    },
    "morning_cloudy": {
        "breed": "welshcorgi",
        "pc": "/images/hero/summer_morning_cloudy_welshcorgi_pc.mp4",
        "m": "/images/hero/summer_morning_cloudy_welshcorgi_m.mp4"
    },
    "morning_rain": {
        "breed": "englishbulldog",
        "pc": "/images/hero/summer_morning_rain_englishbulldog_pc.mp4",
        "m": "/images/hero/summer_morning_rain_englishbulldog_m.mp4"
    },
    "morning_sunny": {
        "breed": "poodle",
        "pc": "/images/hero/summer_morning_sunny_poodle_pc.mp4",
        "m": "/images/hero/summer_morning_sunny_poodle_m.mp4"
    },
    "night_cloudy": {
        "breed": "welshcorgi",
        "pc": "/images/hero/summer_night_cloudy_welshcorgi_pc.mp4",
        "m": "/images/hero/summer_night_cloudy_welshcorgi_m.mp4"
    },
    "night_rain": {
        "breed": "englishbulldog",
        "pc": "/images/hero/summer_night_rain_englishbulldog_pc.mp4",
        "m": "/images/hero/summer_night_rain_englishbulldog_m.mp4"
    },
    "night_sunny": {
        "breed": "poodle",
        "pc": "/images/hero/summer_night_sunny_poodle_pc.mp4",
        "m": "/images/hero/summer_night_sunny_poodle_m.mp4"
    }
} as const;
