export const PET_OBSERVATION_RECORDING_SECONDS = 15;
export const PET_OBSERVATION_MIN_DURATION_SECONDS = 5;
export const PET_OBSERVATION_MAX_DURATION_SECONDS = 20;
export const PET_OBSERVATION_MAX_FILE_MB = 12;
export const PET_OBSERVATION_MAX_FILE_BYTES = PET_OBSERVATION_MAX_FILE_MB * 1024 * 1024;
